name: BSD CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: {}
jobs:
  freebsd:
    name: FreeBSD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/freebsd-vm@a46f291854f624412f94e37b2e6ba64bdb52b5dd # v1.5.1
        with:
          usesh: true
          prepare: pkg install -y rust
          run: |
            cargo build
            cargo test
  openbsd:
    name: OpenBSD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/openbsd-vm@c941015845c0f0c429676840963dc63b226d4f69 # v1.4.5
        with:
          usesh: true
          prepare:  pkg_add rust
          run: |
            cargo build
            cargo test
  netbsd:
    name: NetBSD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/netbsd-vm@fac0a63f3e5244c600cb9ca532d27ee774ecdb4b # v1.4.3
        with:
          usesh: true
          prepare: pkg_add rust
          run: |
            cargo build
            cargo test
  dragonfly:
    name: DragonFly BSD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/dragonflybsd-vm@bc8ccbaa091ce3624c93f2dc328ae48129b07580 # v1.3.1
        with:
          usesh: true
          prepare: pkg install -y rust
          run: |
            cargo build
            cargo test
  midnight:
    name: MidnightBSD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/midnightbsd-vm@1629088a95a63a7273cf57603b13e5e247417549 # v1.0.4
        with:
          usesh: true
          prepare: mport --quiet install rust >/dev/null || true
          run: |
            cargo build
            cargo test
