name: BSD CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: {}
jobs:
  freebsd:
    name: FreeBSD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/freebsd-vm@83b151f58c6047089f4c80eb5ba2039d158ce093 # v1.5.3
        with:
          usesh: true
          prepare: pkg install -y rust
          run: |
            cargo build
            cargo test
  openbsd:
    name: OpenBSD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/openbsd-vm@e6c68b637a12e83519688d115d57d5b0b53923cd # v1.4.6
        with:
          usesh: true
          prepare:  pkg_add rust
          run: |
            cargo build
            cargo test
  netbsd:
    name: NetBSD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/netbsd-vm@00081e82b14bc40114eb97f32b4455306828516b # v1.4.6
        with:
          usesh: true
          prepare: pkg_add rust
          run: |
            cargo build
            cargo test
  dragonfly:
    name: DragonFly BSD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/dragonflybsd-vm@bc8ccbaa091ce3624c93f2dc328ae48129b07580 # v1.3.1
        with:
          usesh: true
          prepare: pkg install -y rust
          run: |
            cargo build
            cargo test
  midnight:
    name: MidnightBSD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/midnightbsd-vm@9a256e5bd9e476e1ac159fa26b997595326ba3a0 # v1.0.5
        with:
          usesh: true
          prepare: mport --quiet install rust >/dev/null || true
          run: |
            cargo build
            cargo test
