name: FreeBSD CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: {}
jobs:
  freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Run FreeBSD VM
        uses: vmactions/freebsd-vm@d1e65811565151536c0c894fff74f06351ed26e6 # v1
        with:
          usesh: true
          prepare: |
            pkg install -y rust
            cargo build
            cargo test
