name: Illumos CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: {}
jobs:
  omnios:
    name: OmniOS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/omnios-vm@9576f0b6d15e7696548409baa533bc0a339caf42 # v1.3.7
        with:
          usesh: true
          prepare: pkg install rust
          run: |
            cargo build
            cargo test
  openindiana:
    name: OpenIndiana
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/openindiana-vm@d82e6302d027df92e66e4fec862e5236c89b305f # v1.1.7
        with:
          usesh: true
          prepare: pkg install developer/lang/rustc developer/gcc-14
          run: |
            cargo build
            cargo test
