name: Illumos CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: {}
jobs:
  omnios:
    name: OmniOS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/omnios-vm@317e4f8069dad8a65e1520808f1a68ef3fd20565 # v1.3.6
        with:
          usesh: true
          prepare: pkg install rust
          run: |
            cargo build
            cargo test
  openindiana:
    name: OpenIndiana
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/openindiana-vm@21e57a45fc8dbfc8b20804ba707c1dad6c271b4f # v1.1.6
        with:
          usesh: true
          prepare: pkg install developer/lang/rustc developer/gcc-14
          run: |
            cargo build
            cargo test
