name: Illumos CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: {}
jobs:
  omnios:
    name: OmniOS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/omnios-vm@d42d894b41dd58cf7e31c194709a1c0fe3d04ace # v1.3.2
        with:
          usesh: true
          prepare: pkg install rust
          run: |
            cargo build
            cargo test
  openindiana:
    name: OpenIndiana
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Run Tests
        uses: vmactions/openindiana-vm@3248e8c61485588528c034a4285242f77efd8b97 # v1.1.3
        with:
          usesh: true
          prepare: pkg install developer/lang/rustc developer/gcc-14
          run: |
            cargo build
            cargo test
