name: Redox CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: {}

env:
  REDOXER_QEMU_ARGS: "-smp 1"

jobs:
  redox:
    runs-on: ubuntu-latest
    container: redoxos/redoxer@sha256:e3054735e7d9e0fb411c82d09a677512d300bf26ec6d4c4b1d6bfe6efbb17e32
    steps:
      - name: Install Toolchain
        run: |
          ln -sT /root/.redoxer ~/.redoxer
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Build
        run: redoxer build
      - name: Test
        run: redoxer test --tests # doc tests aren't supported
